-- ============================================================
-- Wizard Platform — Carta (Productos)
-- Ejecutar en Supabase SQL Editor
-- ============================================================

-- Cocinas
CREATE TABLE IF NOT EXISTS public.cocinas (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  nombre text NOT NULL UNIQUE,
  activa boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Categorías de productos
CREATE TABLE IF NOT EXISTS public.categorias_productos (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  nombre text NOT NULL UNIQUE,
  cocina_id uuid REFERENCES public.cocinas(id),
  orden integer DEFAULT 0,
  activa boolean DEFAULT true
);

-- Productos
CREATE TABLE IF NOT EXISTS public.productos (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  id_fudo integer,
  nombre text NOT NULL,
  categoria_id uuid REFERENCES public.categorias_productos(id),
  precio numeric DEFAULT 0,
  costo numeric DEFAULT 0,
  descripcion text,
  imagen_url text,
  codigo text,
  activo boolean DEFAULT true,
  controlar_stock boolean DEFAULT false,
  vender_sin_stock boolean DEFAULT false,
  permitir_vender_solo boolean DEFAULT true,
  orden integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- Grupos modificadores
CREATE TABLE IF NOT EXISTS public.grupos_modificadores (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  nombre text NOT NULL UNIQUE,
  cantidad_min integer DEFAULT 0,
  cantidad_max integer DEFAULT 1,
  activo boolean DEFAULT true
);

-- Modificadores por producto
CREATE TABLE IF NOT EXISTS public.producto_modificadores (
  producto_id uuid REFERENCES public.productos(id) ON DELETE CASCADE,
  grupo_id uuid REFERENCES public.grupos_modificadores(id),
  PRIMARY KEY (producto_id, grupo_id)
);

-- RLS
ALTER TABLE public.cocinas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias_productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grupos_modificadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto_modificadores ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname='auth_cocinas' AND tablename='cocinas') THEN
    CREATE POLICY auth_cocinas ON public.cocinas FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname='auth_cat_prod' AND tablename='categorias_productos') THEN
    CREATE POLICY auth_cat_prod ON public.categorias_productos FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname='auth_productos' AND tablename='productos') THEN
    CREATE POLICY auth_productos ON public.productos FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname='auth_grupos_mod' AND tablename='grupos_modificadores') THEN
    CREATE POLICY auth_grupos_mod ON public.grupos_modificadores FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname='auth_prod_mod' AND tablename='producto_modificadores') THEN
    CREATE POLICY auth_prod_mod ON public.producto_modificadores FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ── Cocinas ──────────────────────────────────────────────────
INSERT INTO public.cocinas (nombre) VALUES
  ('Barra/Pastelería'),
  ('Cocina')
ON CONFLICT (nombre) DO NOTHING;

-- ── Categorías ───────────────────────────────────────────────
INSERT INTO public.categorias_productos (nombre, cocina_id, orden) VALUES
  ('Bebidas Frías', (SELECT id FROM public.cocinas WHERE nombre='Barra/Pastelería'), 1),
  ('Cafetería', (SELECT id FROM public.cocinas WHERE nombre='Barra/Pastelería'), 2),
  ('Pasteleria', (SELECT id FROM public.cocinas WHERE nombre='Barra/Pastelería'), 3),
  ('Mocktails', (SELECT id FROM public.cocinas WHERE nombre='Barra/Pastelería'), 4),
  ('Promociones', (SELECT id FROM public.cocinas WHERE nombre='Barra/Pastelería'), 5),
  ('Desayunos', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 6),
  ('Pizzas', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 7),
  ('Quesadillas', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 8),
  ('Sandwiches', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 9),
  ('Picoteo', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 10),
  ('Tablas', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 11),
  ('Menú kids', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 12),
  ('Almuerzos', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 13),
  ('Bocadillos Weasley', (SELECT id FROM public.cocinas WHERE nombre='Cocina'), 14),
  ('Agregados', NULL, 15),
  ('Carrito', NULL, 16),
  ('Eventos', NULL, 17),
  ('Halloween', NULL, 18),
  ('Pedidos ya', NULL, 19)
ON CONFLICT (nombre) DO NOTHING;

-- ── Productos ────────────────────────────────────────────────
INSERT INTO public.productos (id_fudo, nombre, categoria_id, precio, costo, activo, controlar_stock, vender_sin_stock, permitir_vender_solo) VALUES
  (302, 'Aceitunas', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (113, 'Agregado Crema chantilli', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 500, 0, true, false, false, false),
  (201, 'Agregado Helado', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 800, 0, true, false, false, false),
  (95, 'Agregado Leche de almendras', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 800, 0, true, true, false, false),
  (163, 'Agregado Leche entera normal', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 500, 0, true, false, false, false),
  (161, 'Agregado Pan desayuno', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 500, 0, false, false, false, true),
  (339, 'Agregado Premium', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (271, 'Agregado Proteína', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2000, 0, true, false, true, false),
  (265, 'Agregado Salsa adicional', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, true, true),
  (162, 'Agregado - Salsa a elección', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, false),
  (338, 'Agregado Simple', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (222, 'Ají', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 890, 0, true, false, false, false),
  (354, 'Canela', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (224, 'Cebolla caramelizada', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 890, 0, true, false, false, false),
  (356, 'Cedrón', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (281, 'Chai Latte', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (282, 'Chai Latte Vainilla', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (223, 'Champiñón', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 890, 0, true, false, false, false),
  (361, 'Chocolate blanco', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (360, 'Chocolate negro', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (355, 'Clavo de olor', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (175, 'Doble Shot', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 1000, 0, true, false, false, false),
  (315, 'Especial con marshmellow', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (267, 'Extra Queso Cheddar', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2000, 0, true, false, true, false),
  (288, 'Frutilla Coco', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (251, 'Hamburguesa falafel', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (254, 'Hierba Manzanilla + Lavanda', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (335, 'Iced tea durazno', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (349, 'Iced tea Frambuesa', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (336, 'Iced tea limón', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (21, 'Ingrediente adicional Paila de huevo', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 500, 0, false, true, false, false),
  (164, 'Ingrediente adicional Sandwich/pizza', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 850, 0, true, false, false, false),
  (234, 'Jamón', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (268, 'Jugo de Chirimoya', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, true, false, false),
  (287, 'Jugo de Frambuesa', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, true, false, false),
  (367, 'Jugo de frutilla', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (269, 'Jugo de Mango', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, true, false, false),
  (298, 'jugo de maracuya', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, true, false, false),
  (286, 'Jugo de Maracuyá', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (270, 'Jugo de Melón', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, true, false, false),
  (273, 'Jugo de Piña', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, true, false, false),
  (262, 'Leche de almendras Chocolate', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 1200, 0, true, false, false, false),
  (331, 'Leche descremada', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (211, 'Leche entera', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (99, 'Leche Sin lactosa', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 800, 0, true, true, false, false),
  (263, 'Leche sin lactosa Chocolate', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 1000, 0, true, false, false, false),
  (368, 'LECHUZA MENSAJERA', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, true),
  (289, 'Mango Piña', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (233, 'Marraqueta', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (301, 'Milkshake del día', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 4499, 0, false, false, false, true),
  (352, 'Mocktail 14 Feb.', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (225, 'Morrón/Pimentón', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 890, 0, true, false, false, false),
  (314, 'Normal sin marshmellow', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (227, 'Palta', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 1000, 0, true, false, false, false),
  (332, 'Pepinillos', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (131, 'Poción con gas', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 500, true, true, false, false),
  (49, 'Poción gaseosa - Coca cola', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2300, 90625, true, false, false, false),
  (132, 'Poción Gaseosa - Coca Zero', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2300, 792, true, false, false, false),
  (114, 'Poción Gaseosa - Fanta/crush', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2300, 1093, true, true, true, false),
  (318, 'Poción gaseosa - Kem', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2300, 0, true, true, false, false),
  (317, 'Poción gaseosa - Limon Soda', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2300, 0, true, true, false, false),
  (115, 'Poción Gaseosa - Sprite', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2300, 1093, true, false, false, false),
  (290, 'Poción Gaseosa - Sprite Zero', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 2300, 0, true, true, false, false),
  (337, 'Poción sin gas', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (226, 'Queso de cabra', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 1000, 0, true, false, false, false),
  (305, 'Queso - Jamón', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (235, 'Queso mozarella', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (304, 'Queso - Salame', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (231, 'Relleno Helado Vainilla', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (230, 'Relleno Manjar', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (217, 'Salsa de ajo', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 500, 0, true, false, false, false),
  (218, 'Salsa de albaca', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 500, 0, true, false, false, false),
  (220, 'Salsa de Merkén', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 500, 0, true, false, false, false),
  (219, 'Salsa mostaza/miel', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (300, 'Sangre de unicornio', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 4500, 9674, true, false, false, false),
  (240, 'Sin agregado', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (241, 'Sin salsa adicional', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, false),
  (242, 'Sin té o café', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (347, 'Smoothie Arándanos', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (345, 'Smoothie Frutilla', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (346, 'Smoothie Mango', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (344, 'Smoothie Plátano', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (371, 'Sopaipillas con pebre', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (370, 'Sopaipillas pasadas', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (214, 'Syrup Avellana', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (246, 'Syrup coco', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (213, 'Syrup de Caramelo', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (295, 'Syrup Pistacho Sin Azucar', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (212, 'Syrup Vainilla', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (239, 'Té Citrus Black', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (364, 'Te con Leche entera', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 250, 0, false, false, false, false),
  (237, 'Té de maracuyá', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (243, 'Té de mora', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (238, 'Té Limonada de naranja', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (236, 'Té Sweet Mango', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (255, 'Té Verde', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (228, 'Tocino', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 1000, 0, true, false, false, false),
  (221, 'Tomate', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 890, 0, true, false, false, false),
  (232, 'Tostadas', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, false, false, false, true),
  (215, 'Versión Hot (Caliente)', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (216, 'Versión Iced (Fría)', (SELECT id FROM public.categorias_productos WHERE nombre='Agregados'), 0, 0, true, false, false, false),
  (248, 'Menu 1 Gryfindor', (SELECT id FROM public.categorias_productos WHERE nombre='Almuerzos'), 12990, 3875, false, true, false, true),
  (249, 'Menu 2 Slytherin', (SELECT id FROM public.categorias_productos WHERE nombre='Almuerzos'), 12990, 3875, false, true, false, true),
  (261, 'Menu 3 Hufflepuf', (SELECT id FROM public.categorias_productos WHERE nombre='Almuerzos'), 12990, 0, false, false, false, true),
  (44, 'Amortentia', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4800, 1093875, true, true, false, true),
  (111, 'Azkaban Shake', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5500, 5892, true, true, false, true),
  (157, 'Brebaje de acónito', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4700, 1670, false, true, false, true),
  (43, 'Butterbeer', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5000, 1246895, false, true, false, true),
  (92, 'Butter beer', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5800, 130624, true, true, false, true),
  (91, 'Elixir de Mandragora', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4800, 0, true, false, false, true),
  (45, 'Elixir de Mandrágora', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4000, 1113875, false, true, false, true),
  (294, 'Elixir original', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4800, 0, true, false, false, true),
  (42, 'Felix Felicis', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5000, 1979565, true, true, false, true),
  (93, 'Feraverto', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5000, 1510, true, true, false, true),
  (48, 'Fera Verto', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4500, 192545, false, true, false, false),
  (348, 'Glacius - Coldbrew', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4000, 0, true, false, false, true),
  (202, 'It''s LeviOsa - Caramel Latte', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5600, 0, true, true, false, true),
  (142, 'Lovegood''s Shake', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4700, 0, false, true, false, true),
  (203, 'Not LeviosA - Matcha menta chips', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5600, 0, true, false, false, true),
  (41, 'Poción Crecehuesos', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5000, 1108175, true, true, false, true),
  (112, 'Poción Energética', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 2500, 1347, true, true, false, true),
  (320, 'Poción Gaseosa', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 2300, 0, true, false, false, true),
  (187, 'Poción gaseosa - Bilz', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 2300, 0, false, false, false, true),
  (313, 'Poción gaseosa - Limón soda', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 2300, 0, false, false, false, true),
  (46, 'Poción Multijugos', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4500, 726425, true, true, false, true),
  (50, 'Poción Translucida', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 2300, 500, true, true, false, true),
  (343, 'Smoothie Longbottom', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 5000, 1105, true, false, false, true),
  (47, 'Veratiserum - Iced Tea', (SELECT id FROM public.categorias_productos WHERE nombre='Bebidas Frías'), 4000, 1191145, true, true, false, true),
  (330, 'Fred y George Weasley', (SELECT id FROM public.categorias_productos WHERE nombre='Bocadillos Weasley'), 6500, 0, false, false, false, true),
  (328, 'Ginny Weasley', (SELECT id FROM public.categorias_productos WHERE nombre='Bocadillos Weasley'), 6500, 0, true, false, false, true),
  (353, 'Percy W.', (SELECT id FROM public.categorias_productos WHERE nombre='Bocadillos Weasley'), 7000, 0, false, true, false, true),
  (327, 'Percy Weasley', (SELECT id FROM public.categorias_productos WHERE nombre='Bocadillos Weasley'), 7000, 0, true, true, false, true),
  (329, 'Ron Weasley', (SELECT id FROM public.categorias_productos WHERE nombre='Bocadillos Weasley'), 5500, 0, true, true, false, true),
  (60, 'Accio Latte', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3500, 6658, false, true, false, true),
  (53, 'Americanum', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3000, 104105, true, true, false, true),
  (133, 'Arresto Momentum', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3500, 107218, true, false, false, true),
  (140, 'Avada Kedavra +18', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4700, 14059, true, true, false, true),
  (59, 'Bombarda', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3600, 117633, true, true, false, true),
  (293, 'Café cortado', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3500, 0, true, false, false, true),
  (56, 'Cappuportus', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3700, 118755, true, true, false, true),
  (136, 'Cappuportus Brulee', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4400, 133852, true, true, false, true),
  (57, 'Cappuportus Special', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4200, 125575, true, true, false, true),
  (66, 'Choco -  Choco', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4000, 100959, true, true, false, true),
  (372, 'Choco Hagrid', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 8500, 201918, true, false, false, true),
  (67, 'Choco - Loco', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4200, 100959, true, true, false, true),
  (341, 'Coldbrew Lattemus', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4000, 0, true, false, false, true),
  (321, 'Confundo/Cortado', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3300, 0, true, false, false, true),
  (139, 'Cruciatus', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4700, 164065, true, true, false, true),
  (358, 'Cupcake Lovegood', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3000, 0, true, false, false, true),
  (52, 'Expresso Doble Patronoum', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3200, 16141, true, true, false, true),
  (51, 'Expresso Patronoum', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 2200, 100905, true, true, false, true),
  (61, 'Gryffindor Tea', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 2500, 183, true, true, false, true),
  (65, 'Hogwarts Teas', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 2000, 390, true, true, false, true),
  (150, 'Hot Accio Latte', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4700, 2966, true, true, false, true),
  (63, 'Hufflepuff Tea', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 2500, 179, true, true, false, true),
  (151, 'Ice Accio Latte', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4490, 2966, false, true, false, true),
  (149, 'Ice Slytherin Latte', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 5690, 3566, false, true, false, true),
  (138, 'Imperio +18', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4700, 137395, true, true, false, true),
  (54, 'Lattemus', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3700, 120785, true, true, false, true),
  (55, 'Lattemus Macchiato', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3500, 126535, false, true, false, true),
  (340, 'Lattemus Nutella', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4500, 1214, true, false, false, true),
  (156, 'Lattemus Special', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4200, 781, true, true, false, true),
  (359, 'Moca Lattemus Snape', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4500, 0, true, false, false, true),
  (58, 'Mochacorpus', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4300, 135505, true, true, false, true),
  (135, 'Mochacorpus Mallow', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4400, 146103, true, true, false, true),
  (165, 'Mochacorpus Special', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 4700, 0, true, false, false, true),
  (137, 'Muffiato', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3100, 101295, true, true, false, true),
  (64, 'Occamy Tea', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 3000, 179, true, true, false, true),
  (362, 'Promo Snitch Latte + MLuna', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 5000, 0, true, false, false, true),
  (365, 'Simple shot', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 0, 0, true, false, false, false),
  (148, 'Slytherin Latte', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 5000, 3566, true, true, false, true),
  (62, 'Slytherin Tea', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 2000, 498286, false, true, false, true),
  (253, 'Te del pensadero', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 2800, 170, false, false, false, true),
  (311, 'Tetera Hogwarts (2p)', (SELECT id FROM public.categorias_productos WHERE nombre='Cafetería'), 5000, 920, true, false, false, true),
  (144, 'Alfajor HP', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 1500, 2490, false, true, false, true),
  (141, 'Cojín HP', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 9990, 0, false, true, false, true),
  (108, 'Galletones de Hagrid', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 1990, 881, false, true, false, true),
  (280, 'Grageas Bolsa', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 7490, 0, false, false, false, true),
  (272, 'Grageas Cajita', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 5990, 1975, false, false, false, true),
  (118, 'Grajeas Harry Potter', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 4490, 2148, false, true, false, true),
  (244, 'huevo pascua', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 7500, 0, false, false, false, true),
  (166, 'Mapa Merodeador', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 3990, 2045, false, false, false, true),
  (145, 'Mini Alfajores', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 400, 0, false, true, false, true),
  (130, 'Mystery bag', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 4990, 1200, false, true, false, true),
  (155, 'Mystery Wand', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 6990, 3072, false, true, false, true),
  (119, 'Rana de Chocolate', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 4990, 3219, false, true, false, true),
  (152, 'The Wizard Bombons', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 3490, 800, false, true, false, true),
  (116, 'Weasley Pops', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 1490, 800, false, true, false, true),
  (209, 'Wizard Cookie', (SELECT id FROM public.categorias_productos WHERE nombre='Carrito'), 1990, 0, false, true, false, true),
  (103, 'Batido de frutas', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 0, 0, false, true, false, true),
  (97, 'Café Americano', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 0, 0, false, true, false, true),
  (98, 'Café Expreso', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 0, 0, false, true, false, true),
  (12, 'El desayuno de Azkaban', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 10490, 5002, false, true, false, true),
  (87, 'El desayuno de Hedwig', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 10990, 5653, false, true, false, true),
  (11, 'Hotcakes de la muerte', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 9490, 4426, false, true, false, true),
  (10, 'Huevo de oro', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 9990, 5357, false, true, false, true),
  (105, 'Jugo del día', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 0, 0, false, true, false, true),
  (160, 'Jugo frutilla', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 0, 0, false, true, false, true),
  (106, 'Jugo Naranja y medialuna', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 0, 0, false, true, false, true),
  (13, 'La palta filosofal', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 9990, 4889, false, true, false, true),
  (107, 'Media luna - Desayunos', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 0, 0, false, true, false, true),
  (96, 'Té Dilma', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 0, 0, false, true, false, true),
  (23, 'Batido de frutos rojos', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 720, 720, true, true, false, false),
  (22, 'Hotcakes + Syrup', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 1095, 1095, true, true, false, false),
  (24, 'Huevo frito + tocino', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 1342, 1342, true, true, false, false),
  (14, 'Jugo de naranja 200cc', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 655, 655, true, true, false, false),
  (17, 'Medialuna', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 205, 205, false, true, false, false),
  (16, 'Muffin chocolate chips', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 887, 887, true, true, false, false),
  (19, 'Paila de huevo', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 811, 811, true, true, false, false),
  (15, 'Té o café Expreso/Americano desayunos.', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 347, 347, true, true, false, false),
  (20, 'Tostadas con mantequilla', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 394, 394, true, true, false, false),
  (25, 'Tostadas + Palta + Tocino', (SELECT id FROM public.categorias_productos WHERE nombre='Desayunos'), 1188, 1188, true, true, false, false),
  (120, 'Butter Beer - Pequeña', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 3900, 0, false, false, false, false),
  (121, 'Choco - Choco HP', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 3300, 0, false, false, false, true),
  (208, 'Filtro de Amor', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 5500, 0, false, false, false, true),
  (122, 'Lattemus HP', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 3000, 0, false, false, false, true),
  (310, 'Mini sopaipotter + pebre (8u)', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 3990, 0, false, false, false, true),
  (206, 'Pizza Amor', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 13990, 0, false, false, false, true),
  (123, 'Poción Gaseosa HP', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 2000, 0, false, false, false, true),
  (207, 'Polvo de Perla', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 4500, 0, false, false, false, true),
  (316, 'Promo 2 capuccino o 2 Latte', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 5500, 0, false, false, false, true),
  (351, 'Promo Hinny', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 21990, 0, false, true, false, true),
  (350, 'Promo Romione', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 12990, 0, false, true, false, true),
  (128, 'Quesadilla Bellatrix Lestrange', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 5000, 0, false, false, false, true),
  (127, 'Quesadilla Newt Scamander', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 5000, 0, false, false, false, true),
  (129, 'Quesadilla Remus Lupin', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 5000, 0, false, false, false, true),
  (308, 'Sortilegios Weasley (3) und', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 3990, 0, false, false, false, true),
  (309, 'Sortilegios Weasley (6) und', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 7490, 0, false, false, false, true),
  (307, 'Tabla Sirius Black', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 14990, 0, false, false, false, true),
  (306, 'Veritaserum', (SELECT id FROM public.categorias_productos WHERE nombre='Eventos'), 5500, 0, false, false, false, true),
  (180, 'Bocadillos de Fluffy', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 12990, 0, false, true, false, true),
  (182, 'Caldero Chorreante', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 3990, 0, false, true, false, true),
  (176, 'Cappupumpkin', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 3600, 0, false, false, false, true),
  (174, 'Colmillos de Nagini', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 6990, 0, false, false, false, true),
  (169, 'Death Eater Hamburguesa', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 10990, 0, false, false, false, true),
  (171, 'El regreso de Lord Voldemort (Quesadillas)', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 10990, 0, false, false, false, true),
  (178, 'Halloween Pops', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 1490, 0, false, true, false, true),
  (177, 'Little Aragog (Hamburguesa niño)', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 5500, 0, false, false, false, true),
  (183, 'Mandrágoras', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 2990, 0, false, true, false, true),
  (172, 'Moco de Troll (Shake)', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 4700, 0, false, false, false, true),
  (170, 'Obscurus Limonada', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 4700, 0, false, false, false, true),
  (173, 'Sectumsempra (Mocachino)', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 4400, 0, false, false, false, true),
  (179, 'Shake Peeves', (SELECT id FROM public.categorias_productos WHERE nombre='Halloween'), 4700, 0, false, true, false, true),
  (89, 'Little Pizza Jamón', (SELECT id FROM public.categorias_productos WHERE nombre='Menú kids'), 5800, 3398, false, true, false, true),
  (88, 'Little Pizza Peperoni', (SELECT id FROM public.categorias_productos WHERE nombre='Menú kids'), 5800, 3696, false, true, false, true),
  (284, 'Little Pizza Tomate', (SELECT id FROM public.categorias_productos WHERE nombre='Menú kids'), 5800, 0, false, false, false, true),
  (256, 'Mocktail Gryffindor', (SELECT id FROM public.categorias_productos WHERE nombre='Mocktails'), 5990, 1516, true, true, false, true),
  (259, 'Mocktail Hufflepuff  +18', (SELECT id FROM public.categorias_productos WHERE nombre='Mocktails'), 5990, 0, true, true, false, true),
  (257, 'Mocktail Ravenclaw +18', (SELECT id FROM public.categorias_productos WHERE nombre='Mocktails'), 5990, 2409, true, true, false, true),
  (258, 'Mocktail Slytherin +18', (SELECT id FROM public.categorias_productos WHERE nombre='Mocktails'), 5990, 0, true, true, false, true),
  (168, 'Alfajor Hogwarts', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 2500, 1100, true, true, false, true),
  (333, 'Brownie Mounstruoso', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 2500, 0, true, true, false, true),
  (342, 'Cheescake oreo', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 5000, 0, true, false, false, true),
  (69, 'Cheesecake 9 3/4', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 5500, 2100, true, true, false, true),
  (374, 'Cupcake chocolate Frog', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3000, 0, true, false, false, true),
  (278, 'Cupcake Happee Birthdae', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3000, 0, false, true, false, true),
  (205, 'Cupcake Hogwarts', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3000, 0, true, false, false, true),
  (357, 'Cupcake Lavender', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3000, 0, true, false, false, true),
  (159, 'Cupcake Patronus', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 2500, 1200, false, true, false, true),
  (74, 'Cupcake Seleccionador', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3000, 900, true, true, false, true),
  (188, 'Cupcake Weasley', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3000, 900, true, true, false, true),
  (75, 'Godric Gryffindor', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 5000, 2142, false, true, false, true),
  (79, 'Happee Birthdae', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 8000, 2500, true, false, false, true),
  (78, 'Helga Hufflepuff', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 4590, 1978, false, true, false, true),
  (334, 'Hogwarts Christmas', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3000, 0, true, true, false, true),
  (283, 'Hogwarts Pops', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 1500, 0, false, true, false, true),
  (363, 'Kowalski Cinamon Roll', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3500, 0, true, false, false, true),
  (373, 'Kowalski cookie', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 1500, 0, true, false, false, true),
  (210, 'La carta de Hedwig - Kuchen', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 5000, 2487, true, false, false, true),
  (70, 'Malfoy''s Pie', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 4600, 1800, true, false, false, true),
  (279, 'Promo Sopaipotter x2', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 6000, 0, false, false, false, true),
  (73, 'Refrigerio de Luna', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 1500, 598, true, false, false, true),
  (366, 'Refrigerio de Luna XL', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3000, 825, true, false, false, true),
  (77, 'Rowena Ravenclaw', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 4990, 0, false, true, false, true),
  (76, 'Salazar Slytherin', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 4590, 1644, false, true, false, true),
  (252, 'Sopaipotter', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 3500, 1900, true, false, false, true),
  (143, 'Tarta Patronus', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 4000, 2000, false, true, false, true),
  (68, 'Tarta Potter', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 4100, 2500, false, true, false, true),
  (102, 'The Wizard cookies', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 2500, 1750, true, true, false, true),
  (72, 'Tortas Wizard', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 5000, 1416, true, false, false, true),
  (71, 'Torta Weasley', (SELECT id FROM public.categorias_productos WHERE nombre='Pasteleria'), 4500, 2000, false, true, false, true),
  (197, 'Ejemplo Aceitunas', (SELECT id FROM public.categorias_productos WHERE nombre='Pedidos ya'), 1, 0, false, false, false, true),
  (198, 'Ejemplo Baño de Chocolate', (SELECT id FROM public.categorias_productos WHERE nombre='Pedidos ya'), 2, 0, false, false, false, true),
  (200, 'Opcional Genérico', (SELECT id FROM public.categorias_productos WHERE nombre='Pedidos ya'), 0, 0, false, false, false, true),
  (199, 'Producto Genérico', (SELECT id FROM public.categorias_productos WHERE nombre='Pedidos ya'), 0, 0, true, false, false, true),
  (195, 'Ejemplo Helado de frutilla', (SELECT id FROM public.categorias_productos WHERE nombre='Pedidos ya'), 100, 0, false, false, false, true),
  (194, 'Ejemplo Pizza Napolitana', (SELECT id FROM public.categorias_productos WHERE nombre='Pedidos ya'), 200, 0, false, false, false, true),
  (196, 'Jugo De Burbujas', (SELECT id FROM public.categorias_productos WHERE nombre='Pedidos ya'), 2500, 0, false, false, false, true),
  (35, 'Aros de Quidditch', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 5850, 2719, false, true, false, true),
  (299, 'Bocaditos de Hedwig', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 4000, 0, true, true, false, true),
  (37, 'Bocaditos de Pixie', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 8900, 3220, true, true, false, true),
  (104, 'Brotes Sauce Boxeador', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 2900, 0, true, false, false, true),
  (153, 'Canastita de Snitch doradas', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 5990, 1818, true, false, false, true),
  (291, 'Huevos de acromántula', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 5990, 1698, true, true, false, true),
  (247, 'James Potter', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 19000, 0, true, true, false, true),
  (184, 'Peter Pettigrew', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 20500, 0, true, true, false, true),
  (38, 'Ramas de sauce boxeador', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 4900, 2513, true, true, false, true),
  (36, 'Varitas de queso', (SELECT id FROM public.categorias_productos WHERE nombre='Picoteo'), 6990, 2483, false, true, false, true),
  (134, 'Agregado Pizza', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 890, 0, false, false, false, true),
  (277, 'Alastor Individual', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 8990, 0, false, false, false, true),
  (30, 'Alastor Moody', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 17500, 600376, true, true, false, true),
  (27, 'Albus Dumbledore', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 13990, 6233, false, true, false, true),
  (181, 'Fenrir Greyback', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 14990, 0, false, true, false, true),
  (275, 'Hagrid Individual', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 6990, 0, false, false, false, true),
  (274, 'Minerva Individual', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 6990, 0, false, false, false, true),
  (26, 'Minerva Mcgonagall', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 12500, 5692, true, false, false, true),
  (126, 'Pizza Alastor Moody - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 7500, 0, true, true, false, true),
  (147, 'Pizza Albus Dumbeldore - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 6490, 0, false, true, false, true),
  (146, 'Pizza Minerva Mcgonagall - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 6000, 0, true, true, false, true),
  (323, 'Pizza Remus Lupin - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 6500, 0, true, true, false, true),
  (124, 'Pizza Rubius Hagrid - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 6500, 0, true, false, false, true),
  (125, 'Pizza Severus Snape - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 6490, 0, false, true, false, true),
  (322, 'Remus Lupin Pizza', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 13500, 0, true, true, false, true),
  (28, 'Rubius Hagrid', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 13500, 43359, true, true, false, true),
  (276, 'Severus Individual', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 8990, 0, false, false, false, true),
  (29, 'Severus Snape', (SELECT id FROM public.categorias_productos WHERE nombre='Pizzas'), 18000, 6082171, false, true, false, true),
  (245, '2 cupcakes', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 3500, 0, false, false, false, true),
  (285, 'Café + Cupcake', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 5500, 0, false, false, false, true),
  (264, 'El Beso del Dementor -15%', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 9340, 0, false, true, true, true),
  (186, 'Promo 2 limonadas', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 0, 0, false, false, false, true),
  (193, 'PROMO AMORTENTIA', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 0, 0, false, false, false, true),
  (312, 'Promo beiblade', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 8000, 0, true, true, false, true),
  (167, 'Promoción 2 Cappuportus + 1 Happee Birthdae', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 11490, 0, false, false, false, true),
  (109, 'Promoción Choco + Galletón', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 5000, 0, false, true, false, true),
  (158, 'Promoción Helga + Crecehuesos Suny', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 8490, 0, false, false, false, true),
  (110, 'Promoción Mochacorpus + Red Velvet', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 8490, 0, false, false, false, true),
  (260, 'Promo Cumple 1 (Pizza)', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 14000, 0, true, false, false, true),
  (303, 'Promo Cumple 2 (Burger)', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 15500, 0, true, false, false, true),
  (189, 'PROMO GRYFFINDOR', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 10000, 0, false, true, false, true),
  (190, 'PROMO HUFFLEPUFF', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 10000, 0, false, true, false, true),
  (204, 'PROMO - Leviosa 2X', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 10000, 0, false, false, false, true),
  (185, 'Promo Pizza + 2 limonadas', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 21490, 0, false, false, false, true),
  (191, 'PROMO RAVENCLAW', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 10000, 0, false, true, false, true),
  (192, 'PROMO SLYTHERIN', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 10000, 0, false, true, false, true),
  (250, '(Viernes) 1 Tabla + 2 limonadas', (SELECT id FROM public.categorias_productos WHERE nombre='Promociones'), 22990, 0, false, false, false, true),
  (32, 'Bellatrix Lestrange XL', (SELECT id FROM public.categorias_productos WHERE nombre='Quesadillas'), 12500, 5309, true, true, false, true),
  (326, 'Bellatrix - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Quesadillas'), 6500, 0, true, false, false, true),
  (325, 'Grindelwald - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Quesadillas'), 6500, 0, true, false, false, true),
  (33, 'Grindelwald XL', (SELECT id FROM public.categorias_productos WHERE nombre='Quesadillas'), 12500, 3430, true, true, false, true),
  (324, 'Newt Scamander - Personal', (SELECT id FROM public.categorias_productos WHERE nombre='Quesadillas'), 6500, 0, true, false, false, true),
  (31, 'Newt Scamander XL', (SELECT id FROM public.categorias_productos WHERE nombre='Quesadillas'), 12500, 3454, true, true, false, true),
  (34, 'Remus Lupin', (SELECT id FROM public.categorias_productos WHERE nombre='Quesadillas'), 9990, 3613, false, true, false, true),
  (154, 'Agregado Sandwich', (SELECT id FROM public.categorias_productos WHERE nombre='Sandwiches'), 890, 0, false, false, false, true),
  (84, 'Beso del dementor', (SELECT id FROM public.categorias_productos WHERE nombre='Sandwiches'), 13500, 4517, true, true, false, true),
  (82, 'Buckbeak', (SELECT id FROM public.categorias_productos WHERE nombre='Sandwiches'), 13000, 23530555, true, true, false, true),
  (83, 'Dobby', (SELECT id FROM public.categorias_productos WHERE nombre='Sandwiches'), 13000, 36772, true, false, false, true),
  (86, 'El pequeño picket', (SELECT id FROM public.categorias_productos WHERE nombre='Sandwiches'), 13000, 25762, true, true, false, true),
  (85, 'Fawks en llamas', (SELECT id FROM public.categorias_productos WHERE nombre='Sandwiches'), 13500, 27175, true, true, false, true),
  (90, 'Little Burger Crookshanks', (SELECT id FROM public.categorias_productos WHERE nombre='Sandwiches'), 5000, 1707, true, true, false, true),
  (81, 'Dolores Umbridge', (SELECT id FROM public.categorias_productos WHERE nombre='Tablas'), 13990, 4206, false, true, false, true),
  (40, 'La que no debe ser nombrada', (SELECT id FROM public.categorias_productos WHERE nombre='Tablas'), 16990, 6471, false, true, false, true),
  (80, 'Tabla Lestrange', (SELECT id FROM public.categorias_productos WHERE nombre='Tablas'), 21990, 9570, false, true, false, true)
ON CONFLICT DO NOTHING;

-- ── Grupos modificadores ────────────────────────────────────
INSERT INTO public.grupos_modificadores (nombre, cantidad_min, cantidad_max) VALUES
  ('Agregado paila', 1, 3),
  ('Agregado shot de café', 0, 2),
  ('Agregados Café/Choco', 0, 3),
  ('Agregados tetera', 1, 3),
  ('Agregados té', 0, 3),
  ('Batido de frutas', 1, 1),
  ('Bebida o energetica', 0, 5),
  ('Elegir Pizza promo', 2, 3),
  ('Elegir Promo Mocktail', 2, 5),
  ('Frio o caliente', 1, 2),
  ('Ingrediente adicional 1', 1, 4),
  ('Jugo de frutilla', 1, 1),
  ('Jugo del día', 1, 1),
  ('Manjar o helado', 0, 2),
  ('Normal o especial', 1, 2),
  ('Opción vegetariana', 0, 2),
  ('Promo Limonadas', 2, 2),
  ('Sabor', 1, 1),
  ('Sabor de jugo', 1, 1),
  ('Sabor iced tea', 1, 1),
  ('Sabor Smoothie', 1, 2),
  ('Salsa adicional', 0, 6),
  ('Selección Bebida', 1, 4),
  ('Selección con o sin gas', 1, 2),
  ('Tipo Chai', 1, 2),
  ('Tipo de chocolate Mocha', 0, 2),
  ('Tipo de Milkshake', 1, 2),
  ('Tipo de pan', 1, 2),
  ('Tipo de Syrup', 1, 2),
  ('Tipo de té', 1, 7),
  ('Tipo Pizza', 1, 2),
  ('Tipo sopaipilla', 1, 2),
  ('Tipos de leche', 1, 3),
  ('Tipos de leche chocolate', 1, 5),
  ('Té o café desayuno', 1, 4)
ON CONFLICT (nombre) DO NOTHING;
