-- ============================================================
-- Ingredientes + Recetas Schema
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ingredientes (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id_fudo      integer,
  nombre       text NOT NULL,
  categoria    text,
  unidad       text DEFAULT 'unid.',
  costo        numeric(12,2) DEFAULT 0,
  proveedor    text,
  controlar_stock boolean DEFAULT false,
  merma        numeric(5,2) DEFAULT 0,
  activo       boolean DEFAULT true,
  creado_en    timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.recetas (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  producto_id     uuid REFERENCES public.productos(id) ON DELETE CASCADE,
  ingrediente_id  uuid REFERENCES public.ingredientes(id) ON DELETE CASCADE,
  cantidad_neta   numeric(12,4) DEFAULT 1,
  unidad          text DEFAULT 'unid.',
  merma           numeric(5,2) DEFAULT 0,
  creado_en       timestamptz DEFAULT now(),
  UNIQUE(producto_id, ingrediente_id)
);

-- RLS
ALTER TABLE public.ingredientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recetas ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname='auth_ingredientes' AND tablename='ingredientes') THEN
    CREATE POLICY auth_ingredientes ON public.ingredientes FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname='auth_recetas' AND tablename='recetas') THEN
    CREATE POLICY auth_recetas ON public.recetas FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- Insert ingredientes
INSERT INTO public.ingredientes (id_fudo, nombre, categoria, unidad, costo, proveedor, controlar_stock, merma) VALUES(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0),
(25, 'Masa de pizza 28cms', 'Bases Panadería - Dulces', 'unid.', 2100, 'Panadería San Juan', true, 0),
(116, 'Masa pizza 15cm', 'Bases Panadería - Dulces', 'unid.', 525, 'Panadería San Juan', true, 0),
(105, 'Pan brioche color', 'Bases Panadería - Dulces', 'unid.', 300, '', false, 0),
(92, 'Pan ciabatta', 'Bases Panadería - Dulces', 'kg', 3150, 'Panadería San Juan', false, 0),
(14, 'Pan de molde', 'Bases Panadería - Dulces', 'unid.', 120, 'Panadería San Juan', true, 0),
(45, 'Tortilla Quesadilla (Burrera)', 'Bases Panadería - Dulces', 'unid.', 449, 'Líder zenteno', true, 0),
(62, 'Agua', 'Bebidas y agua', 'L', 200, '', true, 0),
(68, 'Agua individual', 'Bebidas y agua', 'unid.', 684, 'ICB', true, 0),
(67, 'Bebida 350 ml', 'Bebidas y agua', 'unid.', 880, '', true, 0),
(60, 'Canada dry', 'Bebidas y agua', 'L', 864, 'Líder zenteno', true, 0),
(125, 'Premix/Goma', 'Bebidas y agua', 'L', 6850, '', false, 0),
(124, 'Pulpa Mango', 'Bebidas y agua', 'kg', 5343, '', false, 0),
(48, 'Aros de cebolla', 'Bocadillos congelados', 'kg', 64558, 'ICB', true, 0),
(49, 'Empanadas de queso', 'Bocadillos congelados', 'unid.', 20825, 'ICB', true, 0),
(51, 'Palitos de queso', 'Bocadillos congelados', 'unid.', 387, 'ICB', true, 0),
(37, 'Carne Mechada', 'Carnes, pollo y fiambre', 'kg', 8890, 'Líder zenteno', true, 0),
(78, 'Chorizo', 'Carnes, pollo y fiambre', 'unid.', 204, 'Líder zenteno', true, 0),
(52, 'Costillas baby back ribs', 'Carnes, pollo y fiambre', 'kg', 7366, 'ICB', true, 0),
(109, 'Hamburguesa', 'Carnes, pollo y fiambre', 'unid.', 1500, '', false, 0),
(32, 'Jamón caramelado', 'Carnes, pollo y fiambre', 'unid.', 3613, 'Líder zenteno', true, 0),
(5, 'Jamón sandwich', 'Carnes, pollo y fiambre', 'kg', 7160, 'Líder zenteno', true, 0),
(107, 'Longanicilla', 'Carnes, pollo y fiambre', 'unid.', 200, '', false, 0),
(77, 'Mini Sopaipillas', 'Carnes, pollo y fiambre', 'unid.', 82, 'Líder zenteno', true, 0),
(46, 'Pollo - Pechuga deshuesada', 'Carnes, pollo y fiambre', 'kg', 3558, 'ICB', true, 0),
(100, 'Tapapecho 2', 'Carnes, pollo y fiambre', 'kg', 8990, '', false, 0),
(36, 'Tocino', 'Carnes, pollo y fiambre', 'unid.', 200, 'Vega Afta', true, 0),
(44, 'Aceite de oliva extra virgen', 'Condimentos y otros', 'kg', 8180, 'Líder zenteno', true, 0),
(114, 'Aji color', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(19, 'Azucar', 'Condimentos y otros', 'kg', 1290, 'Líder zenteno', true, 0),
(61, 'Azúcar flor', 'Condimentos y otros', 'kg', 2180, 'Líder zenteno', true, 0),
(59, 'canela', 'Condimentos y otros', 'kg', 28000, 'Líder zenteno', true, 0),
(40, 'Cebolla caramelizada', 'Condimentos y otros', 'kg', 3252, 'The wizard coffee', true, 0),
(112, 'Comino', 'Condimentos y otros', 'kg', 4000, '', false, 0),
(53, 'Eneldo', 'Condimentos y otros', 'kg', 65000, 'Líder zenteno', true, 0),
(16, 'Harina sin polvos de hornear', 'Condimentos y otros', 'kg', 1150, 'Líder zenteno', true, 0),
(94, 'Merken', 'Condimentos y otros', 'kg', 15200, '', false, 0),
(113, 'Pimienta', 'Condimentos y otros', 'kg', 4600, '', false, 0),
(18, 'Polvo de hornear', 'Condimentos y otros', 'kg', 9990, 'Líder zenteno', true, 0),
(17, 'Sal', 'Condimentos y otros', 'kg', 290, 'Líder zenteno', true, 0),
(33, 'Aceitunas laminadas', 'Frutas y verduras', 'kg', 4188, 'ICB', true, 0),
(104, 'Ají', 'Frutas y verduras', 'kg', 3000, '', false, 0),
(93, 'Ajo diente', 'Frutas y verduras', 'unid.', 100, '', false, 0),
(24, 'Berrys congeladas', 'Frutas y verduras', 'kg', 8725, 'Líder zenteno', true, 0),
(82, 'Brócoli', 'Frutas y verduras', 'unid.', 1250, 'Líder zenteno', true, 0),
(83, 'Cebolla', 'Frutas y verduras', 'kg', 1450, 'Líder zenteno', true, 0),
(30, 'Champiñones laminados', 'Frutas y verduras', 'kg', 8750, 'Líder zenteno', true, 0),
(29, 'Choclo desgranado congelado', 'Frutas y verduras', 'kg', 2796, 'ICB', true, 0),
(42, 'Diente de ajo', 'Frutas y verduras', 'unid.', 175, 'Líder zenteno', true, 0),
(115, 'Falafel', 'Frutas y verduras', 'unid.', 370, '', false, 0),
(86, 'Falafel Bolitas', 'Frutas y verduras', 'unid.', 47, 'The wizard coffee', true, 0),
(28, 'Hojas de Albaca', 'Frutas y verduras', 'kg', 10000, 'Vega Afta', true, 0),
(47, 'Hojas de espinaca', 'Frutas y verduras', 'kg', 2580, 'Líder zenteno', true, 0),
(65, 'Hojas de menta', 'Frutas y verduras', 'kg', 33000, '', true, 0),
(102, 'lechuga', 'Frutas y verduras', 'kg', 5000, '', false, 0),
(63, 'Limón sutil', 'Frutas y verduras', 'unid.', 250, 'Líder zenteno', true, 0),
(8, 'Naranja', 'Frutas y verduras', 'kg', 3600, 'Vega Afta', true, 0),
(38, 'Palta', 'Frutas y verduras', 'kg', 5690, 'Líder zenteno', true, 0),
(50, 'Papas fritas rústicas', 'Frutas y verduras', 'kg', 1550, 'Papas rústicas San Fuente', true, 0),
(103, 'Pepinillo', 'Frutas y verduras', 'kg', 3500, '', false, 0),
(81, 'Pimentón Amarillo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(31, 'Pimentón Rojo', 'Frutas y verduras', 'unid.', 1390, 'Líder zenteno', true, 0),
(80, 'Pimentón Verde', 'Frutas y verduras', 'unid.', 890, 'Líder zenteno', true, 0),
(43, 'Piñones', 'Frutas y verduras', 'kg', 8290, 'Líder zenteno', true, 0),
(64, 'Pulpa frutilla', 'Frutas y verduras', 'kg', 4500, '', true, 0),
(7, 'Tomate', 'Frutas y verduras', 'kg', 1850, 'Líder zenteno', true, 0),
(35, 'Tomate cherry', 'Frutas y verduras', 'unid.', 931, 'Líder zenteno', true, 0),
(79, 'Verduras salteadas (650grs)', 'Frutas y verduras', 'unid.', 1645, 'The wizard coffee', true, 0),
(84, 'Zanahoria', 'Frutas y verduras', 'kg', 1150, 'Líder zenteno', true, 0),
(85, 'Zapallo Italiano', 'Frutas y verduras', 'kg', 2790, 'Líder zenteno', true, 0),
(119, 'Base Bocado', 'Lácteos y huevos', 'L', 0, '', false, 0),
(118, 'Base Chocolate', 'Lácteos y huevos', 'L', 0, '', false, 0),
(120, 'Base frutilla', 'Lácteos y huevos', 'L', 0, '', false, 0),
(75, 'Chocolate blanco', 'Lácteos y huevos', 'kg', 13900, 'Líder zenteno', true, 0),
(55, 'Crema chantilly', 'Lácteos y huevos', 'L', 14360, 'Líder zenteno', true, 0),
(21, 'Esencia de vainilla', 'Lácteos y huevos', 'kg', 5340, 'Líder zenteno', true, 0),
(54, 'Helado vainilla', 'Lácteos y huevos', 'L', 2371, 'Líder zenteno', true, 0),
(4, 'Huevo', 'Lácteos y huevos', 'unid.', 234, 'Vega Afta', true, 0),
(70, 'Leche condensada', 'Lácteos y huevos', 'L', 4182, '', true, 0),
(20, 'Leche entera', 'Lácteos y huevos', 'L', 1190, 'Líder zenteno', true, 0),
(15, 'Mantequilla 10g - Desayunos', 'Lácteos y huevos', 'unid.', 154, 'ICB', true, 0),
(22, 'Mantequilla 250g', 'Lácteos y huevos', 'kg', 9800, 'Líder zenteno', true, 0),
(126, 'Matequilla de maní', 'Lácteos y huevos', 'kg', 6980, '', false, 0),
(127, 'Preparado helado', 'Lácteos y huevos', 'L', 2199, '', false, 0),
(111, 'Queso Cheddar', 'Lácteos y huevos', 'unid.', 125, '', false, 0),
(34, 'Queso de cabra', 'Lácteos y huevos', 'kg', 12000, 'Vega Afta', true, 0),
(6, 'Queso Laminado', 'Lácteos y huevos', 'unid.', 377, 'Vega Afta', true, 0),
(27, 'Queso mozarella granulado', 'Lácteos y huevos', 'kg', 7380, 'ICB', true, 0),
(41, 'Queso parmesano', 'Lácteos y huevos', 'kg', 21000, 'Líder zenteno', true, 0),
(108, 'Yogurt Natural', 'Lácteos y huevos', 'unid.', 350, '', false, 0),
(95, 'Mayo Aceituna', 'Salsas', 'kg', 4294, 'The wizard coffee', false, 0),
(96, 'Mayo Ajo', 'Salsas', 'kg', 2500, 'The wizard coffee', false, 0),
(99, 'Mayo Albahaca', 'Salsas', 'kg', 2800, '', false, 0),
(98, 'Mayo Merken', 'Salsas', 'kg', 2656, 'The wizard coffee', false, 0),
(97, 'Mayonesa', 'Salsas', 'kg', 2200, '', false, 0),
(110, 'Mostaza', 'Salsas', 'L', 1600, '', false, 0),
(106, 'Salsa Cheddar', 'Salsas', 'L', 8000, '', false, 0),
(56, 'Salsa de chocolate/caramelo', 'Salsas', 'L', 5650, 'Líder zenteno', true, 0),
(26, 'Salsa de tomate', 'Salsas', 'kg', 3158, 'Líder zenteno', true, 0),
(117, 'Salsa Frambuesa', 'Salsas', 'L', 0, '', false, 0),
(39, 'Salsa pesto', 'Salsas', 'kg', 405437, 'The wizard coffee', true, 0),
(69, 'Cacao amargo', 'Té y café', 'kg', 14290, 'Líder zenteno', true, 0),
(11, 'Café grano - Brave coffee', 'Té y café', 'kg', 32725, 'The wizard coffee', true, 0),
(58, 'Shot expresso - Brave coffee', 'Té y café', 'unid.', 60105, '', true, 0),
(9, 'Té - Bolsa', 'Té y café', 'unid.', 320, '', true, 0),
(71, 'Te chai', 'Té y café', 'unid.', 113, '', true, 0),
(74, 'Té Mango', 'Té y café', 'unid.', 109, '', true, 0),
(72, 'Té Matcha', 'Té y café', 'kg', 428286, '', true, 0),
(73, 'Té Oolong', 'Té y café', 'unid.', 109, '', true, 0),
(88, 'Blue curacao', 'Varios', 'L', 9720, '', false, 0),
(57, 'Decoración', 'Varios', 'unid.', 400, '', false, 0),
(121, 'Galleta Oreo', 'Varios', 'unid.', 0, '', false, 0),
(123, 'Galleta Sunny', 'Varios', 'unid.', 0, '', false, 0),
(122, 'Galleta Tuareg', 'Varios', 'unid.', 0, '', false, 0),
(91, 'Granadina', 'Varios', 'L', 7545, '', false, 0),
(66, 'Hielo frappe', 'Varios', 'kg', 420, 'Hielo Aqualife', true, 0),
(23, 'Hielo normal', 'Varios', 'kg', 875, 'Líder zenteno', true, 0),
(90, 'Licor Manzanilla', 'Varios', 'L', 9720, '', false, 0),
(89, 'Licor Menta', 'Varios', 'L', 9720, '', false, 0),
(87, 'Marshmallow', 'Varios', 'kg', 5299, '', false, 0),
(101, 'Vino blanco', 'Varios', 'L', 2150, '', false, 0)
ON CONFLICT DO NOTHING;
